# Generated by Django 4.1.3 on 2022-12-19 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senttask",
            name="start_time_datetime",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
