# Generated by Django 4.1.3 on 2022-11-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="senttask", old_name="finish_time", new_name="status",
        ),
    ]
