# Generated by Django 3.2.12 on 2022-12-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senttask',
            name='task_output',
            field=models.CharField(max_length=10000),
        ),
    ]
