# Generated by Django 4.1.3 on 2022-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
