# Generated by Django 4.1.3 on 2022-11-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_finish_time_senttask_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="senttask", old_name="task_id", new_name="id",
        ),
    ]
