# Generated by Django 3.2.12 on 2022-12-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_senttask_task_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senttask',
            name='task_output',
        ),
    ]
