# Generated by Django 4.1.3 on 2022-11-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_client_client_num_alter_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_num',
            new_name='client_id',
        ),
    ]
