# Generated by Django 4.1.3 on 2022-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_rename_task_id_senttask_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="senttask",
            name="task_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
