# Generated by Django 4.1.3 on 2022-11-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_client_num_client_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='verison',
            new_name='version',
        ),
    ]
