# Generated by Django 4.1.3 on 2022-12-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="first_seen_date",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="first_seen_time",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="last_seen_date",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="last_seen_time",
            field=models.CharField(default="", max_length=50),
        ),
    ]
