# Generated by Django 4.1.3 on 2022-11-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_senttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senttask',
            name='id',
        ),
        migrations.AddField(
            model_name='senttask',
            name='task_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
