# Generated by Django 4.1.3 on 2022-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_senttask_id_senttask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senttask',
            name='task_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
