# Generated by Django 4.1.3 on 2022-11-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_senttask_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senttask',
            old_name='task_id',
            new_name='id',
        ),
    ]
