# Generated by Django 4.1.3 on 2022-11-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_task_id_senttask_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senttask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
