# Generated by Django 4.1.3 on 2022-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_senttask_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senttask",
            name="finish_time",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="senttask",
            name="start_time",
            field=models.CharField(max_length=60),
        ),
    ]
