# Generated by Django 4.1.3 on 2022-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_alter_senttask_finish_time_alter_senttask_start_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="client_id",),
        migrations.RemoveField(model_name="client", name="host_name",),
        migrations.RemoveField(model_name="client", name="os",),
        migrations.RemoveField(model_name="client", name="status",),
        migrations.RemoveField(model_name="client", name="version",),
        migrations.AddField(
            model_name="client",
            name="_id",
            field=models.CharField(
                default="", max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="hostname",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="ip",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="os_name",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="client",
            name="os_version",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="client",
            name="privileges",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="host_user",
            field=models.CharField(default="", max_length=50),
        ),
    ]
