# Generated by Django 4.1.3 on 2022-11-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_remove_client_client_id_remove_client_host_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client", old_name="_id", new_name="client_id",
        ),
        migrations.RenameField(
            model_name="senttask", old_name="id", new_name="task_id",
        ),
    ]
