# Generated by Django 4.1.3 on 2022-11-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_rename__id_client_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
