services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROTOCOL=${PROTOCOL}
        - CONTROL_SERVER_URL=${CONTROL_SERVER_URL}
        - REMOTE_HOST=${REMOTE_HOST}
        - REMOTE_PORT=${REMOTE_PORT}
        - OBFUSCATION_KEY=${OBFUSCATION_KEY}
        - CLIENT_HTTP_HOST=${CLIENT_HTTP_HOST}
        - CLIENT_HTTP_IP=${CLIENT_HTTP_IP}
    command: client
    restart: always
    container_name: client
    logging:
      options:
        max-size: 100m
    extra_hosts:
      - '${CLIENT_HTTP_HOST}:${CLIENT_HTTP_IP}'