name: frontend_test

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup .env file with testing settings
        working-directory: ./web-server/django_web_server
        run: |
          echo "SECRET_KEY=f178b51cb26d16fd5756b46bd21673c060e1090b993a825081" >> .env
      - run: pip install -r web-server/requirements.txt
      - name: Run flake8
        uses: py-actions/flake8@v2
        with: 
          args: "--max-line-length=120"
          path: "web-server"
