name: Control server tests and linting

#on:
#  pull_request:
#    types: [opened, synchronize]

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./control_server
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        working-directory: ./control_server
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 121 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=121 --statistics
      - name: Setup .env file with testing settings
        working-directory: ./control_server
        run: |
          echo "PREFIX=/control" >> .env
          echo "MOCK_DB=True" >> .env
          echo "MONGO_HOST=" >> .env
          echo "MONGO_PORT=" >> .env
          echo "MONGO_USER=" >> .env
          echo "MONGO_PASSWORD=" >> .env
          echo "MONGO_DATABASE=" >> .env
          echo "MONGO_AUTH_MECHANISM=" >> .env
          echo "DEBUG=False" >> .env
          echo "ID_KEY=some secret key" >> .env
          echo "TRUSTED_PROXIES=172.17.0.0/16,172.18.0.0/16" >> .env
      - name: Test with pytest
        working-directory: ./control_server
        run: |
          pytest tests/
